# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeotecnicalDataExplorer
                                 A QGIS plugin
 Allow to explore data from the geotechnical database model

 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-02-26
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Bruno Rodrigues
        email                : brunorodriguesoli@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import psycopg2

from pandas import read_sql_query


class databaseFunctions: 
############################################################################################################################################################################################
# User methods                                                                       
############################################################################################################################################################################################
    def connectDatabase(dictConnection):
        try:
            connection = psycopg2.connect(user = dictConnection['user'], password = dictConnection['password'], host = dictConnection['host'], port = dictConnection['port'], database = dictConnection['name'])
            return connection
        except (Exception, psycopg2.Error) as error :
            print('Check function databaseFunctions.connectDatabase. Cannot execute function. Reason %s.' % (error)) 
    
    def createExtension(connection):
        try:
            cursor = connection.cursor()
            sql = {'postgis': 'CREATE EXTENSION IF NOT EXISTS postgis;', 'sfcgal':'CREATE EXTENSION IF NOT EXISTS postgis_sfcgal;', 'pggeotec': 'CREATE EXTENSION IF NOT EXISTS pggeotec;'}
            cursor.execute(sql['postgis'])
            connection.commit()
            cursor.execute(sql['sfcgal'])
            connection.commit()
            cursor.execute(sql['pggeotec'])
            connection.commit()
            print('Extension created.')
        except (Exception, psycopg2.Error) as error :
            print('Check function databaseFunctions.createExtenson. Cannot execute function. Reason %s.' % (error))
    
    def dropExtension(connection):
        try:
            cursor = connection.cursor()
            cursor.execute('DROP EXTENSION pggeotec;')
            connection.commit()
            print('Extension droped.')
        except (Exception, psycopg2.Error) as error :
            print('Check function databaseFunctions.createExtenson. Cannot execute function. Reason %s.' % (error))

    def refreshMatviews(connection):
        try:
            cursor = connection.cursor()
            sql = ('SELECT pggeotec.drop_matviews();')
            cursor.execute(sql)
            connection.commit()
            print('Materialized views recreated.')
        except (Exception, psycopg2.Error) as error :
            print('Check function databaseFunctions.refreshMatviews. Cannot execute function. Reason %s.' % (error)) 

    def executeExtensionFunctionNoParameters(connection, functionName):
        try:
            cursor = connection.cursor()
            sql = ('SELECT pggeotec.%s();' % (functionName))
            cursor.execute(sql)
            connection.commit()
            print('%s executed.' % (functionName))
        except (Exception, psycopg2.Error) as error :
            print('Check function databaseFunctions.executeExtensionFunctionNoParameters. Cannot execute function. Reason %s.' % (error)) 

    def executeExtensionFunctionOneParameters(connection, functionName, parameterOne):
        try:
            cursor = connection.cursor()
            sql = ("SELECT pggeotec.%s('%s');" % (functionName, parameterOne))
            cursor.execute(sql)
            connection.commit()
            print('%s executed.' % (functionName))
        except (Exception, psycopg2.Error) as error :
            print('Check function databaseFunctions.executeExtensionFunctionNoParameters. Cannot execute function. Reason %s.' % (error)) 
    
    def consolidationGenerateData(connection, identifier):
        try:
            variable_one, variable_two = [], []
            query = ("SELECT adm_pressao, adm_ind_vaz FROM el.adensamento_medicao WHERE adm_ident = '%s' ORDER BY adm_pk" %(identifier))
            cursor = connection.cursor()
            cursor.execute(query)
            connection.commit()
            query_result = cursor.fetchall()
            for element in query_result:
                variable_one.append(float(element[0]))
                variable_two.append(float(element[1]))
            return variable_one, variable_two
        except Exception as error:
            print ("databaseFunctions.consolidationGenerateData. Reason: %s" %(error))
    
    def granulometryGenerateData(connection, identifier):
        try:
            variable_one, variable_two = [], []
            g_teor_finos, g_teor_gro, g_diam_efet, g_coef_unif, g_coef_curv = 0,0,0,0,0
            g_defloc = 'Sem defloculante'
            query = ("""SELECT g_teor_finos, g_teor_gro, g_diam_efet, g_coef_unif, g_coef_curv, g_defloc
                        FROM el.granulometria WHERE g_ident = '%s'"""%(identifier))
            query2 = ("""SELECT gm_abertura, gm_mat_passa FROM el.granulometria_medicao WHERE gm_ident = '%s' ORDER BY gm_abertura DESC"""%(identifier))
            cursor = connection.cursor()
            cursor.execute(query2)
            connection.commit()
            query_result = cursor.fetchall()
            for element in query_result:
                variable_one.append(float(element[0]))
                variable_two.append(float(element[1]))
            cursor.execute(query)
            connection.commit()
            query_result = cursor.fetchall()
            for element in query_result:
                g_teor_finos = float(element[0])
                g_teor_gro = float(element[1])
                g_diam_efet = float(element[2])
                g_coef_unif = float(element[3])
                g_coef_curv = float(element[4])
                if element[5] == True:
                    g_defloc = 'With deflocculant'
                else:
                    g_defloc = 'Without deflocculant'
            return variable_one, variable_two, g_teor_finos, g_teor_gro, g_diam_efet, g_coef_unif, g_coef_curv, g_defloc
        except Exception as error:
            print ("databaseFunctions.granulometryGenerateData. Reason: %s" %(error))
    
    def atterberbGenerateData(connection, identifier):
        try:
            query = ("SELECT la_lp, la_limit_liq, la_ind_plast, la_arg_ativ FROM el.atterberg WHERE la_ident = '%s';" %(identifier))
            dataframe = read_sql_query(query, connection)
            connection.commit()
            return dataframe
        except Exception as error:
            print ("databaseFunctions.atterberbGenerateData. Reason: %s" %(error))

    def compactacGenerateData(connection, identifier):
        try:
            query = ("SELECT cm_umid_med, cm_densidade FROM el.compactacao_medicao WHERE cm_ident = '%s';" %(identifier))
            dataframe = read_sql_query(query, connection)
            connection.commit()
            return dataframe
        except Exception as error:
            print ("databaseFunctions.compactacGenerateData. Reason: %s" %(error))

    def iscGenerateData(connection, identifier):
        try:
            query = ("SELECT iscm_penet, iscm_pressao FROM el.isc_medicao WHERE iscm_ident = '%s' ORDER BY iscm_penet ASC;" %(identifier))
            dataframe = read_sql_query(query, connection)
            connection.commit()
            return dataframe
        except Exception as error:
            print ("databaseFunctions.iscGenerateData. Reason: %s" %(error))
    
    def piezometerGenerateData(connection, identifier):
        try:
            query = ("SELECT pz_data_med, pz_na_med FROM ic.piezometro WHERE pz_ident = '%s' ORDER BY pz_data_med ASC;" %(identifier))
            query_chuvoso = ("SELECT pz_data_med, pz_na_med FROM ic.piezometro WHERE pz_ident = '%s' AND EXTRACT(MONTH FROM pz_data_med) >= 9 OR EXTRACT(MONTH FROM pz_data_med) <= 4 ORDER BY pz_data_med ASC;" %(identifier))
            query_seco = ("SELECT pz_data_med, pz_na_med FROM ic.piezometro WHERE pz_ident = '%s' AND EXTRACT(MONTH FROM pz_data_med) < 9 OR EXTRACT(MONTH FROM pz_data_med) > 4 ORDER BY pz_data_med ASC;" %(identifier))
            dataframe = read_sql_query(query, connection)
            dataframe_chuvoso = read_sql_query(query_chuvoso, connection)
            dataframe_seco = read_sql_query(query_seco, connection)
            connection.commit()
            return dataframe, dataframe_chuvoso, dataframe_seco
        except Exception as error:
            print ("databaseFunctions.piezometerGenerateData. Reason: %s" %(error))


    def depthWetSPTGenerateData(connection, layer):
        try:
            query_chuvoso = """
            WITH chuvoso AS (
                    SELECT * FROM ic."""+ layer+""" WHERE ((i_data_ini::text LIKE '%-09-%') OR (i_data_ini::text LIKE '%-10-%')
                    OR (i_data_ini::text LIKE '%-11-%') OR (i_data_ini::text LIKE '%-12-%') OR
                    (i_data_ini::text LIKE '%-01-%') OR (i_data_ini::text LIKE '%-02-%')
                    OR (i_data_ini::text LIKE '%-03-%') OR (i_data_ini::text LIKE '%-04-%')) AND spc_final <= 60
                    AND sdg_profund = TRUNC(sdg_profund) AND spc_final IS NOT NULL
                )
                SELECT
                 min(spc_final),
                 PERCENTILE_CONT(0.25) WITHIN GROUP(ORDER BY spc_final) AS q1,
                 avg(spc_final) AS media,
                 PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY spc_final) AS mediana,
                 PERCENTILE_CONT(0.75) WITHIN GROUP(ORDER BY spc_final) AS q3,
                 max(spc_final),
                 sdg_profund
                FROM 
                    chuvoso
                GROUP BY
                    sdg_profund
                ORDER BY
                    sdg_profund ASC
            """
            cursor = connection.cursor()
            cursor.execute(query_chuvoso)
            connection.commit()
            cursor_result = cursor.fetchall()
            profund, minimo, q1, mediano, media, q3, maximo = [],[],[],[],[],[],[]
            for element in cursor_result:
                profund.append(element[6])
                minimo.append(element[0])
                q1.append(element[1])
                media.append(element[2])
                mediano.append(element[3])
                q3.append(element[4])
                maximo.append(element[5])
            return profund, minimo, q1, mediano, media, q3, maximo
        except Exception as error:
            print ("databaseFunctions.depthWetSPTGenerateData. Reason: %s" % (error))

    def depthDrySPTGenerateData(connection, layer):
        try:
            query_chuvoso = """
            WITH seco AS (
                    SELECT * FROM ic."""+ layer+""" WHERE ((i_data_ini::text LIKE '%-05-%') OR (i_data_ini::text LIKE '%-06-%')
                    OR (i_data_ini::text LIKE '%-07-%') OR (i_data_ini::text LIKE '%-08-%')) AND spc_final <= 60
                    AND sdg_profund = TRUNC(sdg_profund) AND spc_final IS NOT NULL
                )
                SELECT
                 min(spc_final),
                 PERCENTILE_CONT(0.25) WITHIN GROUP(ORDER BY spc_final) AS q1,
                 avg(spc_final) AS media,
                 PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY spc_final) AS mediana,
                 PERCENTILE_CONT(0.75) WITHIN GROUP(ORDER BY spc_final) AS q3,
                 max(spc_final),
                 sdg_profund
                FROM 
                    seco
                GROUP BY
                    sdg_profund
                ORDER BY
                    sdg_profund ASC
            """
            cursor = connection.cursor()
            cursor.execute(query_chuvoso)
            connection.commit()
            cursor_result = cursor.fetchall()
            profund, minimo, q1, mediano, media, q3, maximo = [],[],[],[],[],[],[]
            for element in cursor_result:
                profund.append(element[6])
                minimo.append(element[0])
                q1.append(element[1])
                media.append(element[2])
                mediano.append(element[3])
                q3.append(element[4])
                maximo.append(element[5])
            return profund, minimo, q1, mediano, media, q3, maximo
        except Exception as error:
            print ("databaseFunctions.depthDrySPTGenerateData. Reason: %s" % (error))
            
    def depthSPTGenerateData(connection, layer):
        try:
            query = """
            WITH seco AS (
                    SELECT * FROM ic."""+layer+""" WHERE spc_final <= 60
                    AND sdg_profund = TRUNC(sdg_profund) AND spc_final IS NOT NULL
                )
                SELECT
                 min(spc_final),
                 PERCENTILE_CONT(0.25) WITHIN GROUP(ORDER BY spc_final) AS q1,
                 avg(spc_final) AS media,
                 PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY spc_final) AS mediana,
                 PERCENTILE_CONT(0.75) WITHIN GROUP(ORDER BY spc_final) AS q3,
                 max(spc_final),
                 sdg_profund
                FROM 
                    seco
                GROUP BY
                    sdg_profund
                ORDER BY
                    sdg_profund ASC
            """
            cursor = connection.cursor()
            cursor.execute(query)
            connection.commit()
            cursor_result = cursor.fetchall()
            profund, minimo, q1, mediano, media, q3, maximo = [],[],[],[],[],[],[]
            for element in cursor_result:
                profund.append(element[6])
                minimo.append(element[0])
                q1.append(element[1])
                media.append(element[2])
                mediano.append(element[3])
                q3.append(element[4])
                maximo.append(element[5])
            return profund, minimo, q1, mediano, media, q3, maximo
        except Exception as error:
            print ("databaseFunctions.depthSPTGenerateData. Reason: %s" % (error))

    def majority(connectionOne, connectionTwo, gridIds, layerName, variable, majorityDistance, gridName):
        try:
            cursorConnectionOne = connectionOne.cursor()
            sql_prepare = ("""ALTER TABLE %s ADD COLUMN IF NOT EXISTS %s Character varying(254)""" % (gridName, variable))
            cursorConnectionOne.execute(sql_prepare)
            connectionOne.commit()
            cursorConnectionTwo = connectionTwo.cursor()
            for gridID in gridIds:
                sql = ("SELECT pggeotec.majority('%s', '%s','%s', '%s', '%s');" % (majorityDistance, str(int(gridID)), layerName, gridName, variable))
                print(sql)
                cursorConnectionTwo.execute(sql)
                connectionTwo.commit()
        except Exception as error:
            print ("databaseFunctions.majority. Reason: %s" % (error))
        finally:
            connectionOne.close()
            connectionTwo.close()
    
    def idw(connectionOne, connectionTwo, gridIds, layerName, variable, majorityDistance, gridName, numberPoints):
        try:
            cursorConnectionOne = connectionOne.cursor()
            sql_prepare = ("""ALTER TABLE %s ADD COLUMN IF NOT EXISTS idw_%s Character varying(254)""" % (gridName, variable))
            cursorConnectionOne.execute(sql_prepare)
            connectionOne.commit()
            cursorConnectionTwo = connectionTwo.cursor()
            for gridID in gridIds:
                sql = ("SELECT pggeotec.idw('%s', '%s','%s', '%s', '%s', '%s');" % (majorityDistance, str(int(gridID)), layerName, gridName, variable, numberPoints))
                print(sql)
                cursorConnectionTwo.execute(sql)
                connectionTwo.commit()
        except Exception as error:
            print ("databaseFunctions.majority. Reason: %s" % (error))
        finally:
            connectionOne.close()
            connectionTwo.close()

    def recoverDataSPTOrigin(connection, layer, geociu):
        try:
            cursor_legend_origin = connection.cursor()
            cursor_legend_origin.execute("SELECT dm_os_pk, dm_os_desc FROM dom.tb_dom_origem_solo")
            cursor_legend_origin_result = cursor_legend_origin.fetchall()
            connection.commit()
            legend_origin_values = []
            legend_origin_text = []
            k = 0 
            for element_legend_origin in cursor_legend_origin_result:
                legend_origin_values.append(float(element_legend_origin[0]))
                legend_origin_text.append(str(element_legend_origin[1]))
                k += 1

            cursor_percussao = connection.cursor()
            cursor_percussao.execute("SELECT sdg_profund, spc_os_desc FROM ic.%s WHERE sdg_geociu = '%s' ORDER BY sdg_profund ASC " % (layer, geociu))
            cursor_percussao_result = cursor_percussao.fetchall()
            connection.commit()
            profund, var_spc_os_desc  = [], []
            for m in cursor_percussao_result:
                var_spc_os_desc.append(m[1])
                profund.append(m[0])       
            return profund, var_spc_os_desc, legend_origin_values, legend_origin_text
        except Exception as error:
            print ("databaseFunctions.recoverDataSPTOrigin. Reason: %s" % (error))
    
    def recoverDataSPTTexture(connection, layer, geociu):
        try:
            cursor_legend_texture = connection.cursor()
            cursor_legend_texture.execute("SELECT dm_text_pk, dm_text_desc FROM dom.tb_dom_textura_solo")
            cursor_legend_texture_result = cursor_legend_texture.fetchall()
            connection.commit()
            texture_values, texture_text = [], []
            w = 0 
            for element_texture in cursor_legend_texture_result:
                texture_values.append(float(element_texture[0]))
                texture_text.append(str(element_texture[1]))
                w += 1

            cursor_percussao = connection.cursor()
            cursor_percussao.execute("SELECT sdg_profund, spc_text_prim, spc_text_sec, spc_text_comp FROM ic.%s WHERE sdg_geociu = '%s' ORDER BY sdg_profund ASC " % (layer, geociu))
            cursor_percussao_result = cursor_percussao.fetchall()
            connection.commit()
            profund, var_spc_os_desc, var_spc_text_prim, var_spc_text_sec, var_spc_text_comp = [], [], [], [], []
            for m in cursor_percussao_result:
                var_spc_text_prim.append(m[1])
                var_spc_text_sec.append(m[2])
                var_spc_text_comp.append(m[3])
                profund.append(m[0])       
            return profund, var_spc_text_prim, var_spc_text_sec, var_spc_text_comp, texture_values, texture_text
        except Exception as error:
            print ("databaseFunctions.recoverDataSPTTexture. Reason: %s" % (error))
